<?php
/**
 * Writes htdocs/conf/conf.php from the environment, keeping the values
 * generated by the installer (instance id, encryption key...). Run by setup.sh
 * on every `docker compose up`, so URL, database credentials and production
 * mode always follow the environment.
 *
 * Usage: php conf.php <path to conf.php>
 */

$file = $argv[1];
$current = [];
if (is_file($file)) {
    // Read the existing values without leaking them into this scope.
    $current = (static function (string $file): array {
        include $file;
        return array_filter(get_defined_vars(), static fn ($k) => str_starts_with($k, 'dolibarr_'), ARRAY_FILTER_USE_KEY);
    })($file);
}

$code = '/var/www/dolibarr/htdocs';
$env = [
    'dolibarr_main_url_root' => rtrim((string) getenv('DOLI_URL'), '/'),
    'dolibarr_main_document_root' => $code,
    'dolibarr_main_url_root_alt' => '/custom',
    'dolibarr_main_document_root_alt' => $code . '/custom',
    'dolibarr_main_data_root' => '/var/www/documents',
    'dolibarr_main_db_host' => getenv('DB_HOST'),
    'dolibarr_main_db_port' => getenv('DB_PORT'),
    'dolibarr_main_db_name' => getenv('DB_NAME'),
    'dolibarr_main_db_user' => getenv('DB_USER'),
    'dolibarr_main_db_pass' => getenv('DB_PASSWORD'),
    'dolibarr_main_db_type' => 'mysqli',
    'dolibarr_main_db_character_set' => 'utf8mb4',
    'dolibarr_main_db_collation' => 'utf8mb4_unicode_ci',
    // TLS is handled by Caddy (or a proxy in front of it).
    'dolibarr_main_force_https' => '0',
    'dolibarr_main_prod' => filter_var(getenv('DOLI_PROD'), FILTER_VALIDATE_BOOLEAN) ? '1' : '0',
];
$values = array_merge($current, $env);

$php = "<?php\n// Generated by the stack's scripts/conf.php on every `docker compose up`.\n"
    . "// Edit the environment (.env), not this file.\n";
foreach ($values as $name => $value) {
    $php .= '$' . $name . ' = ' . var_export($value, true) . ";\n";
}

if (!is_file($file) || file_get_contents($file) !== $php) {
    if (is_file($file)) {
        chmod($file, 0600);
    }
    file_put_contents($file, $php);
    echo "    conf.php updated\n";
}
chmod($file, 0400);
